apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: young-crawdad-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-hub/young-crawdad-java-springboot-gitops